# Generated by Django 3.2.9 on 2022-09-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('typeChambre', models.CharField(max_length=30)),
                ('prix_chambre', models.PositiveIntegerField(default=0)),
                ('is_disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.PositiveIntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('motif', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('matricule', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=30)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
    ]
