# Generated by Django 3.2.9 on 2022-09-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220912_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix',
            field=models.FloatField(),
        ),
    ]
